### ISSUE TITLE
Error when importing pymc3 in salmon notebook

### ISSUE THREAD

**Issue by dkincaid** [fonnesbeck/gp_regression#4]
Running the second cell in the spawning salmon notebook throws an error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_13157/2218611635.py in <module>
      2 import numpy as np
      3 import pandas as pd
----> 4 import pymc3 as pm
      5 import arviz as az
      6 import matplotlib.pyplot as plt

~/anaconda3/envs/gp_tutorial/lib/python3.7/site-packages/pymc3/__init__.py in <module>
     11 from .model_graph import model_to_graphviz
     12 from . import ode
---> 13 from .stats import *
     14 from .sampling import *
     15 from .step_methods import *

~/anaconda3/envs/gp_tutorial/lib/python3.7/site-packages/pymc3/stats/__init__.py in <module>
     30 compare = map_args(az.compare)
     31 ess = map_args(az.ess)
---> 32 geweke = map_args(az.geweke)
     33 hpd = map_args(az.hpd)
     34 loo = map_args(az.loo)

AttributeError: module 'arviz' has no attribute 'geweke'
```

**Comment by fonnesbeck** [comment]
What version of PyMC3 are you using? Try updating with `pip` or `conda` depending on how you install your Python libraries.

I will close this, as it is not an issue with the notebook, but with your PyMC installation.

**Comment by dkincaid** [comment]
I'm not sure. I followed the instructions for creating a conda environment in the README. I'll dig into that and see if I can figure that out. Your YT video from PyData 2019 is really good. I've been searching for something that I could learn GP's from and finally found this. Thanks.

**Comment by fonnesbeck** [comment]
Thanks! Let me update the environment.yml file and see if that helps.

**Comment by fonnesbeck** [comment]
OK, give it a try using the updated conda environment.

**Comment by dkincaid** [comment]
Thanks! I rebuilt the environment, but still got the error. Then I ran `pip install --update pymc3` inside the environment and now it's working. I really appreciate the help and thanks again for the really good tutorial.
